name: 'Assets Artifacts'
author: 'Guido Scialfa'
description: 'Upload assets to GitHub Artifacts'
runs:
  using: 'node20'
  main: './dist/index.js'
inputs:
  command:
    description: 'Command to execute'
    required: false
  target-dir:
    description: 'Target directory to upload'
    required: false
  can-push:
    description: 'Whenever the assets shall be pushed'
    required: false
    default: 'true'
