#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Save the current working directory
original_dir=$(pwd)

# Define color codes
GREEN='\033[0;32m'
NC='\033[0m' # No Color

echo -e "${GREEN}Building $dir...${NC}"
yarn prettify
yarn build
git add .
